
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Cinzel|Open+Sans:300,300italic,400,400italic,600,600italic,700,700italic,800,800italic|Open+Sans+Condensed:300,300italic,700|Didact+Gothic">
  <link rel="stylesheet" href="style.css">
  <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
</head>
<body>
<?php include "nav.php";?>


<div class="rconparent">

<div class="rcon">

  <h1>Bachelor of Science in Information Science</h1>
  ​The purposed of this study is to design a centralize network plan of Ilocos Sur Polytechnic State College, Tagudin Campus.
  ​This study aimed to: design a network infrastructure plan for Ilocos Sur Polytechnic State College, Tagudin Campus through equipment and connections; and to test the reliability of the plan.
  ​As basis on the design of the network infrastructure plan, the necessary requirements were gathered regarding the current blueprint of the Tagudin Campus. Some of the offices has its own internet connection where there is no control in the use of internet and some offices used wired connection. They do not used file sharing because the computers their using are not connected at all. The researchers reviewed and analyzed all the requirements.
  ​The researches designed a physical and network layout. After finalizing the design, the researchers setup a wireless network plan with the use of network equipment such as access point, routers and switch. The office of the Executive Campus Administrator was set with the equipment mentioned.
  ​The researchers used ping to determine the reliability of the developed plan for the ISPSC, Tagudin Campus.

  <h1>Master of Science in Education</h1>
  ​PALOAY, SHARLEEN MAE V. (2019) IMPLEMENTATION OF CHILD PROTECTION POLICY IN GALIMUYOD-SIGAY-G. DEL PILAR (GSP) DISTRICT. Master of Science in Education, major in General Education. Ilocos Sur Polytechnic State College, Graduate School, Tagudin, Ilocos Sur.
  ​This stufy assessed the implementation of Child Protection Policy in Galimuyod-Sigay-G. Del Pilar (GSP) District during the School Year 2018-2019. Specifically it sought to answers for the following questions: What is the level of CCP implementation as perceived by school heads and teachers in the elementary schools of GSP District as to: 1.1. duties and responsibilities of school heads; 1.2. duties and responsibilities of personnel; 1.3. duties and responsibilities of pupils; 1.4. establishment of a Child Protection Committee; 1.5. conduct of capacity building; and 1.6. conduct of protective and remedial measures? 2. What is the extent of prevalence of the following prohibitive acts against learners as perceived by school heads, teachers and parents; 2.1. child abuse; 2.2. child discrimination; 2.3. child exploitation; 2.4. violence against children; 2.5. corporal punishment; 2.6. bullying; 2.6.1. physical; 2.6.2. verbal; 2.6.3. social; and 2.6.4. electronics? 3. What is the degree of seriousness of the problems of school administrators in the implementation of the Child Protection Policy as experienced and perceived by the school heads, teachers and parents along; 3.1. Policy-based problems; 3.1.1. Procedure; 3.1.2. Personnel; 3.1.3. Standards and Principles; 3.2. School-based problems; 3.2.1. Time; 3.2.2. Materials and equipment; 3.2.3. Financial resources; 3.2.4. Parents’ attitude towards discipline; 3.3; Cultural factors; 3.3.1. Ilocano values; and 3.3.22 Child rearing practices; 4. Is there significant difference between the perceptions of school heads, teachers and parents in the extent of prohibitive acts against learners? 5. Is here significant difference between the perceptions of school heads, teachers and parents in the degree of seriousness implementation of child protection policy? 6. What material can be developed  to iomprove the implementation of Child Protection Policy in Galimuyod-Sigay-G. Del Pilar District? 7. What is the level  of acceptability of Strengthening Child Protection primer in Galimuyod-Sigay-G. Del Pilar District?
  ​The researcher used the descriptive-developmental research design and adopted questionnaire was utilized in gathering data from the total enumeration of 150 school heads and teachers and 325 parents through random sampling in GSP District. Mean was used to treat the data.
  ​The following are the findings: The level of implementation of DepEd Child Protection Policy along duties and responsibilities of school heads, duties and responsibilities of school personnel, duties and responsibilities of learners, establishment of child protection committee, conduct of capability building and conduct of protective and remedial measures were highly implemented as evidenced by the ratings 4.07, 4.20, 4.05, 4.12, 3.88, and 3.76 respectively. The extent of prevalence of the prohibitive acts against learners were poorly prevalent as perceived by school heads and teachers with an overall mean rating of 1.39; parents with 2.00 and overall grand mean of 1.70. The degree of seriousness in the implementation of the Child Protection Policy were moderately serious as perceived by the school heads and teachers with an overall mean rating of 2.78; parents with 2.88 and overall grand mean of 2.83; the proposed primer of Child Protection Policy was very highly acceptable with a mean rating of 4.64.
  ​Conclusions are: the level of CPP implementation as perceived by school heads and teachers in the elementary schools of GSP District as to duties and responsibilities of school heads, personnel and learners, the establishment of a Child Protection Committee, the conduct of capacity building and conduct of protective measure will greatly raise the awareness and strengthen the execution of DepEd Child Protection Policy; The extent of prevalence of prohibitive acts such as child abuse, child discrimination, child exploitation, violence against children, corporal punishment and bullying against learners indicate that occurrences of such acts still exist in the district; The degree of seriousness on the problems in the implementation of DepEd Child Protection Policy as perceived by school administrators and teachers, and parents along policy-based constraints, school-based constraints and cultural factors can help the Children Protection Committee identify limiting factors that hinder the realization of Child Protection Policy; The primer on Child Protection is beneficial to improve the implementation of the DepEd Child Protection Policy; The output, Primer, is appropriate, functional, responsive and timely.

  <h1>Institute of Business Management and Entrepreneurship</h1>
  Executive Summary
  ​Nasalukag Farm Supply is a farm supply store opted to cater the needs of the local farmers of Suyo, Ilocos Sur, wherein farming is the main economic activity in the municipality, and as per interview and observation, goods are being purchased at the Yellow Market which seems to be the nearest location for purchasing wherein fare or freight is so costly entailing burden to customers. Suyo public market will be the best location because it will be the center of economic activity in the place that it facilitates accessibility for the customer. A survey has been undertaken to find out the availability of the product and services of the proposed business. As a result 84.91% of the farmer’s population will be the target market. Its products will focus mainly on agricultural supplies such as pesticides, insecticides, herbicides, feeds, and etc. For its Product Strategy-brand preferences of the costumers will be identify and served to customers. Price will be set higher than the existing prices at the Yellow Market to cover up the freight expenses. Networking cite such as face book will be utilize for promotional strategy as majority of the public now enjoying and using. Due to its geographical characteristic Suyo is prone to landslide which may suspend business operation-with this concern establishing stock is projected and maintained stable operation.
  Technical Summary
  ​The proposed business will be offering its customers the best kind of agricultural supply in Suyo. Along with the different types of pesticide, insecticide, fertilizers and other livestock supply. This will be situated in public market, Suyo, Ilocos Sur. The proposed business will be operating from 8:00 am to 5:00pm, and will be opened from Monday to Saturday. The store will be equipped with wooden racks for seeds, glass built rack intended for chemical products like pesticide and insecticide, table for keeping and filing of records, and cabinet for products display.
  Management Summary
  ​The proposed business will start its operation on the grand opening of the public market of Suyo, Ilocos Sur. The business is a “sole proprietorship” for of business ownership, and will be operated by the owner, who will serve as the cashier. There will be two male personnel to be hired for the position of Sales Person and Bagger/ Helper, who will be in charge for the everyday operation. All employees shall receive their benefits and respective wages with their corresponding specifications. Nasalukag Store will be in accordance with the requirements mandated by the DOLE before the store can become fully operational. The store will conduct policies and procedures for the attainment of productivity and efficiency that will lead to organizational and personal growth.
  Financial Summary
  ​The business opted to be a sole proprietor type of business; hence the capital will be provided by the owner. The proposed business will be using a beginning capital of three million pesos (Php. 3,000,000.00). It is projected that the business will increase its purchase and sales by 4% annually. Taxes and licenses Expense will decrease by Php. 250.00 if fees permit and license will not change.

  <h1>Socio-Economic Summary</h1>
  ​The proposed business will contribute to the socio-economic development of the community by generating new job opportunities which will somehow reduce unemployment in the community. It will also help the residents to save money, minimize expenses and time providing that the proposed business is available and accessible, which will make customer more convenient to purchase their needs in farming.

  <h1>Bachelor of Arts in English Language</h1>
  ​Orpia, Bryan G. (2016). Reading Comprehension Skills of Senior AB Students of Ilocos Sur Polytechnic State College, Tagudin Campus. Bachelor of Arts in English Language.
  ​This study attempted to look into the level of Reading Comprehension Skills in English of the AB student of Ilocos Sur Polytechnic State College Tagudin Campus for the school year 2015-2016. Specifically, the following sub-problems were answered: The profile of the AB-Senior Student of Ilocos Sur Polytechnic State College, Tagudin Campus in terms of sex, occupation of parents, monthly income of the family, and type of school graduated from; the level of reading comprehension of the AB Senior Students of Ilocos Sur Polytechnic State College, Tagudin Campus along literal, reorganization, inferential, evaluation, appreciation and reading comprehension skills of the AB Senior students related to their sex, occupation of parents, monthly income of the family, and type of school graduated from.
  ​Based of the date gathered, the following were the salient findings: 1. The AB Senior Students Tagudin Campus during the school year 2015-2016 were predominantly females, 76%. 2. The respondent performed very satisfactory in their test of reading comprehension skills as attested by a general average of 7.94% and sex, occupation of parents, monthly income of the family, and type of school graduated from is not a predictor of reading comprehension skills of the senior students.
  ​From the findings made and the conclusions drawn, the researcher highly recommends the following: 1.) Students should encourage to make reading as a habit; 2) Admission requirements being imposed by the AB Senior Students should be improved and strictly imposed; 3) English teacher should remedy ways to improve the reading comprehension skills of their students like requiring them to have even just a pocket dictionary everyday reference in case of new words.

  <h1>Bachelor of Arts in Psychology</h1>
  Joven, Cricha Mae M.; Lacsamana, Jie Marie A.; CAbugawan, Lyca B. (2019) Shame on me, Shame on you: Body Image and Body Shaming Experiences of Students of the College of Arts and Sciences. Bachelor of Arts in Psychology. Ilocos Sur Polytechnic State College, Tagudin, Ilocos Sur
  The study was conducted to determine the perception of the respondents on their body image among college students of Ilocos Sur Polytechnic State College under College of Arts and Sciences for the school year 2018-2019. Specifically, the study determined the extent on body shaming experiences of the respondents.
  There were 120 respondents and their answers were analyzed through weighted mean and descriptive equivalent rating scale. The study found out that I can also be concluded that the respondents become more confident of themselves however, the body shaming experiences increases.
  It is recommended, then, that the school needs to establish an awareness campaign about bullying regards to body shaming and body image.

  <h1>Bachelor of Arts in Social Sciences</h1>
  ​Baturi, Jherwin C., Goze, Joleen Mae L., Lardizabal, Danielle V., Lardizabal, Laramae G., Velasco, Phoebe Marie M. (2019) Lenten Cultural Practices of Barangay San Tiburcio, Salcedo, Ilocos Sur. Qualitative methods in social research.
  ​This study aimed to document the existing Lenten Cultural Practices of Barangay San Tiburcio, Salcedo, Ilocos Sur, the researchers used qualitative method of research and utilized the barangay captain and four (4) catholic devotee in the Barangay as informants. An unstructured interview was used to gather data of the study.
  ​Based on the informants, the following are Lenten cultural practices of the barangay that need to be preserved: kuros-kuros, palaspas, misa, fasting and abstinence, pammuggo, almsgiving, seven last words, agep, libot, sabet-sabet, Easter Sunday and Pasyon.
  ​Based on the data gathered in this study, the following are the conclusions arrived at: 1. there were old/ traditional and new way of Lenten cultural practices that are being practiced in Barangay San Tiburcio, Salcedo, Ilocos Sur. 2. Barangay San Tiburcio, Salcedo, Ilocos Surhas a rich culture in terms of practicing the “Semana Santa”/ Holly Week which are still practiced up to the present. 3. With all the different Lenten practices in Barangay San Tiburcio, Salcedo, Ilocos Sur, the respondents has a very strong belief in practicing the “Semana Santa”/ Holy Week and considers to be that time repentance of their sins which strengthens one’s own faith and achieving spiritual growth. 4. Barangay San Tiburcio, Salcedo, Ilocos Sur manifest Lenten cultural practices which are still observed by them. These Lenten practices are manifestations of their beliefs, way of life as one community and must preserve up to the next generation.

  <h1 class="h1r">Bachelor of Science in Mathematics</h1>
  <h1 class="h1r">Bachelor of Public Administration</h1>
  <h1 class="h1r">Bachelor of Secondary Education (major BPED)</h1>
  <h1 class="h1r">Bachelor of Secondary Education (major Filipino)</h1>
  <h1 class="h1r">Bachelor of Secondary Education (major English)</h1>
  <h1 class="h1r">Bachelor of Secondary Education (major Social Science)</h1>
  <h1 class="h1r">Bachelor of Secondary Education (major Mathematics)</h1>
  <h1 class="h1r">Bachelor of Secondary Education (major Biological Science)</h1>
  <h1 class="h1r">Bachelor of Elementary Education</h1>

</div>

</div>
</body>
</html>